title: Gridwise
email: jowens@ece.ucdavis.edu
description: WebGPU compute primitives in JavaScript
baseurl: "/gridwise"
url: "https://gridwise-webgpu.github.io"
github_username: gridwise-webgpu

markdown: kramdown
remote_theme: jekyll/minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Only show About in header navigation
header_pages:
  - about.markdown

exclude:
  - misc/
  - Gemfile
  - Gemfile.lock
